service: ebliq-landingpage-backend

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  timeout: 5

custom:
  pythonRequirements:
    dockerizePip: true
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - .serverless/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - .vscode

functions:
  predict_answer:
    handler: handler.pre_register
    memorySize: 128
    events:
      - http:
          path: ""
          method: post
          cors: true

plugins:
  - serverless-python-requirements
